### ISSUE TITLE
Fix godot download url for godot 3.x.x linux headless to official godot github release url

### ISSUE THREAD

**Issue by lukepayyapilli** [ceceppa/godot-gut-ci#11]
Hi! Thank you for writing this. The tuxfamily download link for godot is broken. You just need to update the download in line 26 in your `init-and-run-tests.sh` from:

`wget https://downloads.tuxfamily.org/godotengine/${GODOT_VERSION}/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip`

to:

`wget https://github.com/godotengine/godot/releases/download/${GODOT_VERSION}-stable/Godot_v${GODOT_VERSION}-stable_linux_headless.64.zip`

PR: https://github.com/ceceppa/godot-gut-ci/pull/12

**Comment by ceceppa** [comment]
Thanks for the PR
