### ISSUE TITLE
Doesnt recursively find tests in subdirectories

### ISSUE THREAD

**Issue by token-cjg** [ceceppa/godot-gut-ci#3]
Thanks for creating this project!

While kicking the tires of this action I noticed that only tests one level down are found, i.e. for this structure:

test
-unit
--test_basic1.gd
--subfolder1
---test_basic2.gd

Will run test_basic1.gd, but test/unit/subfolder1/test_basic2.gd would not be executed.

**Comment by ceceppa** [comment]
Hi, I'm going to do some test later today

**Comment by ceceppa** [comment]
Now you can pass custom parameters to the GUT runner, so to handle multiple folders you can use something like:

`-gdir=res://test/unit,res://test/unit/subfolder1,res://test/unit/subfolder2`
