### ISSUE TITLE
Missing glibc's version 2.28 for Godot 4.2

### ISSUE THREAD

**Issue by xorblo-doitus** [ceceppa/godot-gut-ci#9]
When using this action with Godot 4.2, I get this error:
```
/usr/local/bin/godot: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /usr/local/bin/godot)
```
It seems due to [this update](https://github.com/godotengine/build-containers/pull/131).

I think I managed to work around this error by changing the Ubuntu version in DockerFile from 18.04  to 22.04, but I don't really know the implications behind the scenes.
https://github.com/ceceppa/godot-gut-ci/blob/209aaf452c657fcc841837e0e77c86e370b98696/Dockerfile#L1

Action's output [before](https://github.com/xorblo-doitus/Bloc-notes-plus-plus/actions/runs/7141108813/job/19447757536) and [after](https://github.com/xorblo-doitus/Bloc-notes-plus-plus/actions/runs/7150302473/job/19473442664) this work around. (There is still an error, but it seems not related to that missing version 2.28 of glibc because the version changed from 2.27 to 2.35)

**Comment by Saplings-Projects** [comment]
Same problem here, with the same error message when using `godot_version: 4.2`

**Comment by anthonyronda** [comment]
Could we get a version bump as well?

0.2.0 is the latest from October, and the PR is from December

For anyone else reading this thinking they don't want to use @/main, I recommend this line in your yaml
`uses: ceceppa/godot-gut-ci@83e8b452eec0683f59445f34e16e0bd0ff16144c`

That's the commit hash for the latest commit as of Aug 2024

**Comment by ceceppa** [comment]
@anthonyronda, thanks for pointing this out. Added new release.
